CREATE TABLE ISSUESLISTS
(
    ID serial primary key,
    NAME VARCHAR(100)
);

CREATE TABLE ISSUES
(
    ID SERIAL PRIMARY KEY,
    ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
    SUMMARY VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)
);

SELECT * FROM ISSUESLISTS;
SELECT * FROM ISSUES;

INSERT INTO ISSUESLISTS (NAME) VALUES ("ToDo");
INSERT INTO ISSUESLISTS (NAME) VALUE ("In progress");
INSERT INTO ISSUESLISTS (NAME) VALUE ("Done");

COMMIT ;
SELECT * FROM ISSUESLISTS;
SELECT * FROM ISSUES;

INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, "A1", "A11", 1);
COMMIT ;
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, "A2", "A22", 1);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, "A3", "A33", 1);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, "A4", "A44", 1);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, "A5", "A55", 1);
COMMIT ;

INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, "B1", "B11", 1);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, "B2", "B22", 2);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, "B3", "B33", 3);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, "B4", "B44", 4);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, "B5", "B55", 5);
COMMIT ;

INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, "C1", "C11", 1);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, "C2", "C22", 2);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, "C3", "C33", 3);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, "C4", "C44", 4);
INSERT INTO ISSUES ( ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, "C5", "C55", 5);
COMMIT ;