select I.SUMMARY, II.NAME
from ISSUES I JOIN ISSUESLISTS II ON I.ISSUESLIST_ID = II.ID;

select I.SUMMARY, U.FIRSTNAME, U.LASTNAME
from ISSUES I JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID;

select U.FIRSTNAME, U.LASTNAME, COUNT(*) AS QUESTS_NUMBER
from ISSUES I JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY U.LASTNAME, U.FIRSTNAME;